import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface PlayerData {
  name: string;
  position: string;
  age: number;
  image_url: string | null;
  international_caps: number;
}

// Player data for ALL WK 2026 countries
const countryPlayers: Record<string, { name: string; position: string; age: number; caps: number }[]> = {
  'België': [
    { name: "Thibaut Courtois", position: "Goalkeeper", age: 32, caps: 102 },
    { name: "Koen Casteels", position: "Goalkeeper", age: 31, caps: 24 },
    { name: "Jan Vertonghen", position: "Defender", age: 37, caps: 154 },
    { name: "Toby Alderweireld", position: "Defender", age: 35, caps: 127 },
    { name: "Timothy Castagne", position: "Defender", age: 28, caps: 45 },
    { name: "Arthur Theate", position: "Defender", age: 24, caps: 18 },
    { name: "Wout Faes", position: "Defender", age: 26, caps: 20 },
    { name: "Axel Witsel", position: "Midfielder", age: 35, caps: 130 },
    { name: "Kevin De Bruyne", position: "Midfielder", age: 33, caps: 102 },
    { name: "Youri Tielemans", position: "Midfielder", age: 27, caps: 68 },
    { name: "Amadou Onana", position: "Midfielder", age: 23, caps: 24 },
    { name: "Orel Mangala", position: "Midfielder", age: 26, caps: 12 },
    { name: "Leandro Trossard", position: "Forward", age: 29, caps: 42 },
    { name: "Jeremy Doku", position: "Forward", age: 22, caps: 28 },
    { name: "Romelu Lukaku", position: "Forward", age: 31, caps: 116 },
    { name: "Loïs Openda", position: "Forward", age: 24, caps: 22 },
    { name: "Charles De Ketelaere", position: "Forward", age: 23, caps: 18 },
    { name: "Johan Bakayoko", position: "Forward", age: 21, caps: 8 },
    { name: "Dodi Lukebakio", position: "Forward", age: 27, caps: 15 },
    { name: "Arne Engels", position: "Midfielder", age: 21, caps: 5 },
  ],
  'Nederland': [
    { name: "Bart Verbruggen", position: "Goalkeeper", age: 22, caps: 12 },
    { name: "Justin Bijlow", position: "Goalkeeper", age: 26, caps: 5 },
    { name: "Virgil van Dijk", position: "Defender", age: 33, caps: 68 },
    { name: "Nathan Aké", position: "Defender", age: 29, caps: 55 },
    { name: "Matthijs de Ligt", position: "Defender", age: 25, caps: 48 },
    { name: "Denzel Dumfries", position: "Defender", age: 28, caps: 52 },
    { name: "Jurriën Timber", position: "Defender", age: 23, caps: 22 },
    { name: "Micky van de Ven", position: "Defender", age: 23, caps: 10 },
    { name: "Frenkie de Jong", position: "Midfielder", age: 27, caps: 58 },
    { name: "Tijjani Reijnders", position: "Midfielder", age: 26, caps: 18 },
    { name: "Ryan Gravenberch", position: "Midfielder", age: 22, caps: 18 },
    { name: "Teun Koopmeiners", position: "Midfielder", age: 26, caps: 22 },
    { name: "Xavi Simons", position: "Midfielder", age: 21, caps: 20 },
    { name: "Jerdy Schouten", position: "Midfielder", age: 27, caps: 15 },
    { name: "Memphis Depay", position: "Forward", age: 30, caps: 98 },
    { name: "Cody Gakpo", position: "Forward", age: 25, caps: 38 },
    { name: "Donyell Malen", position: "Forward", age: 25, caps: 35 },
    { name: "Steven Bergwijn", position: "Forward", age: 27, caps: 35 },
    { name: "Wout Weghorst", position: "Forward", age: 32, caps: 35 },
    { name: "Brian Brobbey", position: "Forward", age: 22, caps: 8 },
    { name: "Joshua Zirkzee", position: "Forward", age: 23, caps: 5 },
  ],
  'Duitsland': [
    { name: "Manuel Neuer", position: "Goalkeeper", age: 38, caps: 121 },
    { name: "Marc-André ter Stegen", position: "Goalkeeper", age: 32, caps: 42 },
    { name: "Antonio Rüdiger", position: "Defender", age: 31, caps: 70 },
    { name: "Jonathan Tah", position: "Defender", age: 28, caps: 32 },
    { name: "Nico Schlotterbeck", position: "Defender", age: 25, caps: 18 },
    { name: "David Raum", position: "Defender", age: 26, caps: 24 },
    { name: "Benjamin Henrichs", position: "Defender", age: 27, caps: 20 },
    { name: "Joshua Kimmich", position: "Midfielder", age: 29, caps: 95 },
    { name: "İlkay Gündoğan", position: "Midfielder", age: 34, caps: 82 },
    { name: "Toni Kroos", position: "Midfielder", age: 34, caps: 114 },
    { name: "Jamal Musiala", position: "Midfielder", age: 21, caps: 38 },
    { name: "Florian Wirtz", position: "Midfielder", age: 21, caps: 28 },
    { name: "Robert Andrich", position: "Midfielder", age: 30, caps: 15 },
    { name: "Leroy Sané", position: "Forward", age: 28, caps: 67 },
    { name: "Serge Gnabry", position: "Forward", age: 29, caps: 48 },
    { name: "Kai Havertz", position: "Forward", age: 25, caps: 52 },
    { name: "Niclas Füllkrug", position: "Forward", age: 31, caps: 20 },
    { name: "Deniz Undav", position: "Forward", age: 28, caps: 8 },
    { name: "Maximilian Beier", position: "Forward", age: 21, caps: 5 },
  ],
  'Frankrijk': [
    { name: "Mike Maignan", position: "Goalkeeper", age: 29, caps: 18 },
    { name: "Alphonse Areola", position: "Goalkeeper", age: 31, caps: 8 },
    { name: "Dayot Upamecano", position: "Defender", age: 26, caps: 28 },
    { name: "William Saliba", position: "Defender", age: 23, caps: 18 },
    { name: "Theo Hernández", position: "Defender", age: 27, caps: 38 },
    { name: "Jules Koundé", position: "Defender", age: 25, caps: 32 },
    { name: "Ibrahima Konaté", position: "Defender", age: 25, caps: 15 },
    { name: "Aurélien Tchouaméni", position: "Midfielder", age: 24, caps: 38 },
    { name: "Eduardo Camavinga", position: "Midfielder", age: 21, caps: 22 },
    { name: "N'Golo Kanté", position: "Midfielder", age: 33, caps: 58 },
    { name: "Antoine Griezmann", position: "Forward", age: 33, caps: 130 },
    { name: "Kylian Mbappé", position: "Forward", age: 26, caps: 82 },
    { name: "Ousmane Dembélé", position: "Forward", age: 27, caps: 48 },
    { name: "Marcus Thuram", position: "Forward", age: 27, caps: 25 },
    { name: "Randal Kolo Muani", position: "Forward", age: 26, caps: 22 },
    { name: "Olivier Giroud", position: "Forward", age: 38, caps: 137 },
    { name: "Kingsley Coman", position: "Forward", age: 28, caps: 58 },
    { name: "Bradley Barcola", position: "Forward", age: 22, caps: 8 },
  ],
  'Spanje': [
    { name: "Unai Simón", position: "Goalkeeper", age: 27, caps: 42 },
    { name: "David Raya", position: "Goalkeeper", age: 29, caps: 5 },
    { name: "Aymeric Laporte", position: "Defender", age: 30, caps: 48 },
    { name: "Dani Carvajal", position: "Defender", age: 32, caps: 52 },
    { name: "Marc Cucurella", position: "Defender", age: 26, caps: 18 },
    { name: "Robin Le Normand", position: "Defender", age: 27, caps: 12 },
    { name: "Alejandro Grimaldo", position: "Defender", age: 29, caps: 8 },
    { name: "Rodri", position: "Midfielder", age: 28, caps: 62 },
    { name: "Pedri", position: "Midfielder", age: 22, caps: 32 },
    { name: "Gavi", position: "Midfielder", age: 20, caps: 28 },
    { name: "Fabián Ruiz", position: "Midfielder", age: 28, caps: 38 },
    { name: "Dani Olmo", position: "Midfielder", age: 26, caps: 42 },
    { name: "Lamine Yamal", position: "Forward", age: 17, caps: 18 },
    { name: "Nico Williams", position: "Forward", age: 22, caps: 22 },
    { name: "Álvaro Morata", position: "Forward", age: 32, caps: 80 },
    { name: "Ferran Torres", position: "Forward", age: 24, caps: 48 },
    { name: "Mikel Oyarzabal", position: "Forward", age: 27, caps: 35 },
  ],
  'Engeland': [
    { name: "Jordan Pickford", position: "Goalkeeper", age: 30, caps: 62 },
    { name: "Aaron Ramsdale", position: "Goalkeeper", age: 26, caps: 5 },
    { name: "Harry Maguire", position: "Defender", age: 31, caps: 65 },
    { name: "John Stones", position: "Defender", age: 30, caps: 75 },
    { name: "Kyle Walker", position: "Defender", age: 34, caps: 92 },
    { name: "Kieran Trippier", position: "Defender", age: 34, caps: 54 },
    { name: "Luke Shaw", position: "Defender", age: 29, caps: 35 },
    { name: "Marc Guéhi", position: "Defender", age: 24, caps: 18 },
    { name: "Declan Rice", position: "Midfielder", age: 25, caps: 58 },
    { name: "Jude Bellingham", position: "Midfielder", age: 21, caps: 38 },
    { name: "Kobbie Mainoo", position: "Midfielder", age: 19, caps: 8 },
    { name: "Cole Palmer", position: "Midfielder", age: 22, caps: 15 },
    { name: "Phil Foden", position: "Forward", age: 24, caps: 42 },
    { name: "Bukayo Saka", position: "Forward", age: 23, caps: 42 },
    { name: "Harry Kane", position: "Forward", age: 31, caps: 98 },
    { name: "Marcus Rashford", position: "Forward", age: 27, caps: 60 },
    { name: "Anthony Gordon", position: "Forward", age: 23, caps: 8 },
    { name: "Ollie Watkins", position: "Forward", age: 28, caps: 18 },
    { name: "Ivan Toney", position: "Forward", age: 28, caps: 12 },
  ],
  'Portugal': [
    { name: "Diogo Costa", position: "Goalkeeper", age: 25, caps: 22 },
    { name: "Rui Patrício", position: "Goalkeeper", age: 36, caps: 108 },
    { name: "Rúben Dias", position: "Defender", age: 27, caps: 55 },
    { name: "Pepe", position: "Defender", age: 41, caps: 141 },
    { name: "João Cancelo", position: "Defender", age: 30, caps: 58 },
    { name: "Nuno Mendes", position: "Defender", age: 22, caps: 28 },
    { name: "António Silva", position: "Defender", age: 21, caps: 15 },
    { name: "Bruno Fernandes", position: "Midfielder", age: 30, caps: 68 },
    { name: "Vitinha", position: "Midfielder", age: 24, caps: 28 },
    { name: "João Palhinha", position: "Midfielder", age: 29, caps: 32 },
    { name: "Bernardo Silva", position: "Midfielder", age: 30, caps: 92 },
    { name: "Cristiano Ronaldo", position: "Forward", age: 39, caps: 212 },
    { name: "Rafael Leão", position: "Forward", age: 25, caps: 32 },
    { name: "João Félix", position: "Forward", age: 25, caps: 35 },
    { name: "Diogo Jota", position: "Forward", age: 28, caps: 38 },
    { name: "Gonçalo Ramos", position: "Forward", age: 23, caps: 18 },
    { name: "Francisco Conceição", position: "Forward", age: 22, caps: 10 },
  ],
  'Brazilië': [
    { name: "Alisson", position: "Goalkeeper", age: 32, caps: 68 },
    { name: "Ederson", position: "Goalkeeper", age: 31, caps: 22 },
    { name: "Marquinhos", position: "Defender", age: 30, caps: 82 },
    { name: "Éder Militão", position: "Defender", age: 26, caps: 32 },
    { name: "Danilo", position: "Defender", age: 33, caps: 58 },
    { name: "Wendell", position: "Defender", age: 31, caps: 12 },
    { name: "Guilherme Arana", position: "Defender", age: 27, caps: 15 },
    { name: "Casemiro", position: "Midfielder", age: 32, caps: 75 },
    { name: "Lucas Paquetá", position: "Midfielder", age: 27, caps: 52 },
    { name: "Bruno Guimarães", position: "Midfielder", age: 27, caps: 22 },
    { name: "Raphinha", position: "Forward", age: 28, caps: 32 },
    { name: "Vinícius Júnior", position: "Forward", age: 24, caps: 35 },
    { name: "Rodrygo", position: "Forward", age: 23, caps: 22 },
    { name: "Endrick", position: "Forward", age: 18, caps: 8 },
    { name: "Richarlison", position: "Forward", age: 27, caps: 52 },
    { name: "Gabriel Martinelli", position: "Forward", age: 23, caps: 15 },
    { name: "Savinho", position: "Forward", age: 20, caps: 5 },
  ],
  'Argentinië': [
    { name: "Emiliano Martínez", position: "Goalkeeper", age: 32, caps: 48 },
    { name: "Franco Armani", position: "Goalkeeper", age: 38, caps: 18 },
    { name: "Nicolás Otamendi", position: "Defender", age: 36, caps: 108 },
    { name: "Cristian Romero", position: "Defender", age: 26, caps: 32 },
    { name: "Lisandro Martínez", position: "Defender", age: 26, caps: 22 },
    { name: "Nahuel Molina", position: "Defender", age: 26, caps: 28 },
    { name: "Nicolás Tagliafico", position: "Defender", age: 32, caps: 52 },
    { name: "Rodrigo De Paul", position: "Midfielder", age: 30, caps: 58 },
    { name: "Leandro Paredes", position: "Midfielder", age: 30, caps: 62 },
    { name: "Enzo Fernández", position: "Midfielder", age: 23, caps: 28 },
    { name: "Alexis Mac Allister", position: "Midfielder", age: 25, caps: 42 },
    { name: "Lionel Messi", position: "Forward", age: 37, caps: 186 },
    { name: "Ángel Di María", position: "Forward", age: 36, caps: 145 },
    { name: "Lautaro Martínez", position: "Forward", age: 27, caps: 58 },
    { name: "Julián Álvarez", position: "Forward", age: 24, caps: 32 },
    { name: "Paulo Dybala", position: "Forward", age: 31, caps: 38 },
    { name: "Alejandro Garnacho", position: "Forward", age: 20, caps: 12 },
  ],
  // NIEUWE LANDEN WK 2026
  'Noorwegen': [
    { name: "Ørjan Nyland", position: "Goalkeeper", age: 34, caps: 25 },
    { name: "Mads Hermansen", position: "Goalkeeper", age: 24, caps: 8 },
    { name: "Kristoffer Ajer", position: "Defender", age: 26, caps: 42 },
    { name: "Leo Østigård", position: "Defender", age: 24, caps: 22 },
    { name: "David Møller Wolfe", position: "Defender", age: 27, caps: 18 },
    { name: "Birger Meling", position: "Defender", age: 30, caps: 28 },
    { name: "Stian Gregersen", position: "Defender", age: 29, caps: 15 },
    { name: "Martin Ødegaard", position: "Midfielder", age: 26, caps: 58 },
    { name: "Sander Berge", position: "Midfielder", age: 27, caps: 52 },
    { name: "Fredrik Aursnes", position: "Midfielder", age: 29, caps: 18 },
    { name: "Morten Thorsby", position: "Midfielder", age: 28, caps: 35 },
    { name: "Patrick Berg", position: "Midfielder", age: 27, caps: 12 },
    { name: "Erling Haaland", position: "Forward", age: 24, caps: 35 },
    { name: "Alexander Sørloth", position: "Forward", age: 29, caps: 45 },
    { name: "Joshua King", position: "Forward", age: 33, caps: 68 },
    { name: "Antonio Nusa", position: "Forward", age: 19, caps: 8 },
    { name: "Ola Solbakken", position: "Forward", age: 26, caps: 12 },
    { name: "Mohamed Elyounoussi", position: "Forward", age: 30, caps: 52 },
    { name: "Jørgen Strand Larsen", position: "Forward", age: 24, caps: 15 },
    { name: "Oscar Bobb", position: "Forward", age: 21, caps: 5 },
  ],
  'Schotland': [
    { name: "Angus Gunn", position: "Goalkeeper", age: 28, caps: 15 },
    { name: "Craig Gordon", position: "Goalkeeper", age: 41, caps: 75 },
    { name: "Andrew Robertson", position: "Defender", age: 30, caps: 72 },
    { name: "Kieran Tierney", position: "Defender", age: 27, caps: 42 },
    { name: "Scott McKenna", position: "Defender", age: 28, caps: 35 },
    { name: "Grant Hanley", position: "Defender", age: 33, caps: 48 },
    { name: "Jack Hendry", position: "Defender", age: 29, caps: 25 },
    { name: "John McGinn", position: "Midfielder", age: 30, caps: 68 },
    { name: "Scott McTominay", position: "Midfielder", age: 28, caps: 52 },
    { name: "Callum McGregor", position: "Midfielder", age: 31, caps: 58 },
    { name: "Billy Gilmour", position: "Midfielder", age: 23, caps: 28 },
    { name: "Ryan Christie", position: "Midfielder", age: 29, caps: 42 },
    { name: "Stuart Armstrong", position: "Midfielder", age: 32, caps: 38 },
    { name: "Che Adams", position: "Forward", age: 28, caps: 28 },
    { name: "Lyndon Dykes", position: "Forward", age: 29, caps: 35 },
    { name: "Lawrence Shankland", position: "Forward", age: 29, caps: 15 },
    { name: "Ryan Fraser", position: "Forward", age: 30, caps: 28 },
    { name: "James Forrest", position: "Forward", age: 33, caps: 42 },
    { name: "Ben Doak", position: "Forward", age: 19, caps: 5 },
    { name: "Tommy Conway", position: "Forward", age: 22, caps: 8 },
  ],
  'Oostenrijk': [
    { name: "Patrick Pentz", position: "Goalkeeper", age: 27, caps: 18 },
    { name: "Heinz Lindner", position: "Goalkeeper", age: 34, caps: 25 },
    { name: "David Alaba", position: "Defender", age: 32, caps: 108 },
    { name: "Kevin Danso", position: "Defender", age: 26, caps: 32 },
    { name: "Maximilian Wöber", position: "Defender", age: 26, caps: 28 },
    { name: "Philipp Lienhart", position: "Defender", age: 28, caps: 22 },
    { name: "Stefan Posch", position: "Defender", age: 27, caps: 35 },
    { name: "Philipp Mwene", position: "Defender", age: 30, caps: 18 },
    { name: "Marcel Sabitzer", position: "Midfielder", age: 30, caps: 78 },
    { name: "Konrad Laimer", position: "Midfielder", age: 27, caps: 42 },
    { name: "Nicolas Seiwald", position: "Midfielder", age: 24, caps: 22 },
    { name: "Florian Grillitsch", position: "Midfielder", age: 29, caps: 38 },
    { name: "Christoph Baumgartner", position: "Midfielder", age: 25, caps: 42 },
    { name: "Romano Schmid", position: "Midfielder", age: 24, caps: 15 },
    { name: "Marko Arnautović", position: "Forward", age: 35, caps: 115 },
    { name: "Michael Gregoritsch", position: "Forward", age: 30, caps: 48 },
    { name: "Patrick Wimmer", position: "Forward", age: 23, caps: 12 },
    { name: "Maximilian Entrup", position: "Forward", age: 27, caps: 8 },
    { name: "Andreas Weimann", position: "Forward", age: 33, caps: 42 },
    { name: "Benedikt Pichler", position: "Forward", age: 27, caps: 5 },
  ],
  'Canada': [
    { name: "Milan Borjan", position: "Goalkeeper", age: 37, caps: 68 },
    { name: "Maxime Crépeau", position: "Goalkeeper", age: 30, caps: 22 },
    { name: "Alphonso Davies", position: "Defender", age: 24, caps: 52 },
    { name: "Moise Bombito", position: "Defender", age: 24, caps: 18 },
    { name: "Alistair Johnston", position: "Defender", age: 26, caps: 35 },
    { name: "Kamal Miller", position: "Defender", age: 27, caps: 28 },
    { name: "Derek Cornelius", position: "Defender", age: 27, caps: 22 },
    { name: "Richie Laryea", position: "Defender", age: 29, caps: 32 },
    { name: "Stephen Eustáquio", position: "Midfielder", age: 28, caps: 42 },
    { name: "Ismaël Koné", position: "Midfielder", age: 22, caps: 25 },
    { name: "Samuel Piette", position: "Midfielder", age: 30, caps: 58 },
    { name: "Jonathan Osorio", position: "Midfielder", age: 32, caps: 62 },
    { name: "Mark-Anthony Kaye", position: "Midfielder", age: 30, caps: 28 },
    { name: "Jonathan David", position: "Forward", age: 25, caps: 52 },
    { name: "Cyle Larin", position: "Forward", age: 29, caps: 68 },
    { name: "Tajon Buchanan", position: "Forward", age: 25, caps: 42 },
    { name: "Liam Millar", position: "Forward", age: 25, caps: 22 },
    { name: "Junior Hoilett", position: "Forward", age: 34, caps: 48 },
    { name: "Jacen Russell-Rowe", position: "Forward", age: 22, caps: 8 },
    { name: "Theo Bair", position: "Forward", age: 24, caps: 12 },
  ],
  'Mexico': [
    { name: "Guillermo Ochoa", position: "Goalkeeper", age: 39, caps: 138 },
    { name: "Luis Malagón", position: "Goalkeeper", age: 27, caps: 15 },
    { name: "César Montes", position: "Defender", age: 27, caps: 52 },
    { name: "Johan Vásquez", position: "Defender", age: 26, caps: 35 },
    { name: "Jorge Sánchez", position: "Defender", age: 26, caps: 38 },
    { name: "Jesús Gallardo", position: "Defender", age: 29, caps: 72 },
    { name: "Julián Araujo", position: "Defender", age: 23, caps: 22 },
    { name: "Edson Álvarez", position: "Midfielder", age: 27, caps: 68 },
    { name: "Luis Romo", position: "Midfielder", age: 29, caps: 42 },
    { name: "Érick Gutiérrez", position: "Midfielder", age: 29, caps: 38 },
    { name: "Carlos Rodríguez", position: "Midfielder", age: 27, caps: 28 },
    { name: "Diego Lainez", position: "Midfielder", age: 24, caps: 22 },
    { name: "Hirving Lozano", position: "Forward", age: 29, caps: 68 },
    { name: "Raúl Jiménez", position: "Forward", age: 33, caps: 98 },
    { name: "Alexis Vega", position: "Forward", age: 27, caps: 28 },
    { name: "Henry Martín", position: "Forward", age: 32, caps: 35 },
    { name: "Santiago Giménez", position: "Forward", age: 23, caps: 28 },
    { name: "Uriel Antuna", position: "Forward", age: 27, caps: 42 },
    { name: "Roberto Alvarado", position: "Forward", age: 26, caps: 22 },
    { name: "Julián Quiñones", position: "Forward", age: 27, caps: 15 },
  ],
  'USA': [
    { name: "Matt Turner", position: "Goalkeeper", age: 30, caps: 35 },
    { name: "Ethan Horvath", position: "Goalkeeper", age: 29, caps: 12 },
    { name: "Sergiño Dest", position: "Defender", age: 24, caps: 35 },
    { name: "Antonee Robinson", position: "Defender", age: 27, caps: 42 },
    { name: "Chris Richards", position: "Defender", age: 24, caps: 18 },
    { name: "Tim Ream", position: "Defender", age: 37, caps: 62 },
    { name: "Miles Robinson", position: "Defender", age: 27, caps: 28 },
    { name: "Joe Scally", position: "Defender", age: 21, caps: 15 },
    { name: "Tyler Adams", position: "Midfielder", age: 25, caps: 42 },
    { name: "Weston McKennie", position: "Midfielder", age: 26, caps: 52 },
    { name: "Yunus Musah", position: "Midfielder", age: 22, caps: 38 },
    { name: "Giovanni Reyna", position: "Midfielder", age: 22, caps: 28 },
    { name: "Brenden Aaronson", position: "Midfielder", age: 24, caps: 38 },
    { name: "Christian Pulisic", position: "Forward", age: 26, caps: 68 },
    { name: "Timothy Weah", position: "Forward", age: 24, caps: 38 },
    { name: "Folarin Balogun", position: "Forward", age: 23, caps: 18 },
    { name: "Ricardo Pepi", position: "Forward", age: 22, caps: 22 },
    { name: "Josh Sargent", position: "Forward", age: 24, caps: 25 },
    { name: "Brandon Vazquez", position: "Forward", age: 26, caps: 12 },
    { name: "Haji Wright", position: "Forward", age: 26, caps: 15 },
  ],
  'Panama': [
    { name: "Luis Mejía", position: "Goalkeeper", age: 33, caps: 42 },
    { name: "Orlando Mosquera", position: "Goalkeeper", age: 28, caps: 18 },
    { name: "Michael Murillo", position: "Defender", age: 28, caps: 58 },
    { name: "Fidel Escobar", position: "Defender", age: 29, caps: 52 },
    { name: "Harold Cummings", position: "Defender", age: 32, caps: 68 },
    { name: "Eric Davis", position: "Defender", age: 33, caps: 72 },
    { name: "César Blackman", position: "Defender", age: 26, caps: 28 },
    { name: "Aníbal Godoy", position: "Midfielder", age: 34, caps: 98 },
    { name: "Adalberto Carrasquilla", position: "Midfielder", age: 26, caps: 42 },
    { name: "Édgar Bárcenas", position: "Midfielder", age: 31, caps: 62 },
    { name: "Alberto Quintero", position: "Midfielder", age: 37, caps: 82 },
    { name: "José Luis Rodríguez", position: "Midfielder", age: 27, caps: 35 },
    { name: "Rolando Blackburn", position: "Forward", age: 36, caps: 48 },
    { name: "José Fajardo", position: "Forward", age: 28, caps: 38 },
    { name: "Ismael Díaz", position: "Forward", age: 27, caps: 22 },
    { name: "Eduardo Guerrero", position: "Forward", age: 26, caps: 18 },
    { name: "César Yanis", position: "Forward", age: 25, caps: 22 },
    { name: "Freddy Góndola", position: "Forward", age: 30, caps: 32 },
    { name: "Abdiel Ayarza", position: "Midfielder", age: 27, caps: 25 },
    { name: "Yoel Bárcenas", position: "Forward", age: 29, caps: 28 },
  ],
  'Haïti': [
    { name: "Josué Duverger", position: "Goalkeeper", age: 26, caps: 18 },
    { name: "Alexandre Duval", position: "Goalkeeper", age: 28, caps: 12 },
    { name: "Ricardo Adé", position: "Defender", age: 26, caps: 22 },
    { name: "Carlens Arcus", position: "Defender", age: 27, caps: 28 },
    { name: "Alex Christian", position: "Defender", age: 24, caps: 15 },
    { name: "Mechack Jérôme", position: "Defender", age: 34, caps: 52 },
    { name: "Jean-Sylvain Babin", position: "Defender", age: 29, caps: 18 },
    { name: "Derrick Etienne", position: "Midfielder", age: 28, caps: 42 },
    { name: "Melchie Dumornay", position: "Midfielder", age: 21, caps: 8 },
    { name: "Kevin Lafrance", position: "Defender", age: 34, caps: 35 },
    { name: "Bryan Alceus", position: "Midfielder", age: 23, caps: 12 },
    { name: "Steeven Saba", position: "Midfielder", age: 28, caps: 22 },
    { name: "Mondy Prunier", position: "Midfielder", age: 27, caps: 18 },
    { name: "Frantzdy Pierrot", position: "Forward", age: 29, caps: 28 },
    { name: "Duckens Nazon", position: "Forward", age: 30, caps: 42 },
    { name: "Carnejy Antoine", position: "Forward", age: 24, caps: 15 },
    { name: "Nathanaël Hérissé", position: "Forward", age: 21, caps: 5 },
    { name: "Christiano François", position: "Forward", age: 26, caps: 12 },
    { name: "Ricardo Ade", position: "Midfielder", age: 25, caps: 18 },
    { name: "Wilde-Donald Guerrier", position: "Forward", age: 35, caps: 58 },
  ],
  'Curaçao': [
    { name: "Eloy Room", position: "Goalkeeper", age: 35, caps: 42 },
    { name: "Jairzinho Pieter", position: "Goalkeeper", age: 28, caps: 12 },
    { name: "Cuco Martina", position: "Defender", age: 35, caps: 58 },
    { name: "Juriën Gaari", position: "Defender", age: 30, caps: 32 },
    { name: "Darryl Lachman", position: "Defender", age: 35, caps: 48 },
    { name: "Vurnon Anita", position: "Midfielder", age: 35, caps: 35 },
    { name: "Leandro Bacuna", position: "Midfielder", age: 33, caps: 45 },
    { name: "Juninho Bacuna", position: "Midfielder", age: 27, caps: 28 },
    { name: "Kenji Gorré", position: "Midfielder", age: 30, caps: 22 },
    { name: "Michaël Maria", position: "Midfielder", age: 32, caps: 35 },
    { name: "Rangelo Janga", position: "Forward", age: 32, caps: 38 },
    { name: "Jafar Arias", position: "Forward", age: 31, caps: 28 },
    { name: "Elson Hooi", position: "Forward", age: 32, caps: 42 },
    { name: "Gevaro Nepomuceno", position: "Forward", age: 33, caps: 38 },
    { name: "Shaquille Pinas", position: "Defender", age: 26, caps: 18 },
    { name: "Shanon Carmelia", position: "Forward", age: 24, caps: 12 },
    { name: "Gervane Kastaneer", position: "Forward", age: 28, caps: 22 },
    { name: "Brently Kuwas", position: "Midfielder", age: 27, caps: 15 },
    { name: "Jurdrich Comenencia", position: "Defender", age: 25, caps: 8 },
    { name: "Orlando Engelaar", position: "Forward", age: 26, caps: 10 },
  ],
  'Algerije': [
    { name: "Raïs M'Bolhi", position: "Goalkeeper", age: 38, caps: 92 },
    { name: "Alexandre Oukidja", position: "Goalkeeper", age: 36, caps: 15 },
    { name: "Ramy Bensebaini", position: "Defender", age: 29, caps: 58 },
    { name: "Aïssa Mandi", position: "Defender", age: 33, caps: 78 },
    { name: "Youcef Atal", position: "Defender", age: 28, caps: 28 },
    { name: "Djamel Benlamri", position: "Defender", age: 34, caps: 35 },
    { name: "Hocine Benayada", position: "Defender", age: 27, caps: 12 },
    { name: "Ismaël Bennacer", position: "Midfielder", age: 27, caps: 52 },
    { name: "Ramiz Zerrouki", position: "Midfielder", age: 28, caps: 22 },
    { name: "Nabil Bentaleb", position: "Midfielder", age: 30, caps: 62 },
    { name: "Houssem Aouar", position: "Midfielder", age: 26, caps: 18 },
    { name: "Hicham Boudaoui", position: "Midfielder", age: 25, caps: 15 },
    { name: "Riyad Mahrez", position: "Forward", age: 33, caps: 92 },
    { name: "Saïd Benrahma", position: "Forward", age: 29, caps: 32 },
    { name: "Islam Slimani", position: "Forward", age: 36, caps: 98 },
    { name: "Andy Delort", position: "Forward", age: 33, caps: 18 },
    { name: "Baghdad Bounedjah", position: "Forward", age: 33, caps: 48 },
    { name: "Yacine Brahimi", position: "Forward", age: 35, caps: 72 },
    { name: "Mohamed Amoura", position: "Forward", age: 24, caps: 12 },
    { name: "Amine Gouiri", position: "Forward", age: 24, caps: 8 },
  ],
  'Egypte': [
    { name: "Mohamed El-Shenawy", position: "Goalkeeper", age: 35, caps: 52 },
    { name: "Ahmed El-Shenawy", position: "Goalkeeper", age: 33, caps: 18 },
    { name: "Ahmed Hegazi", position: "Defender", age: 33, caps: 58 },
    { name: "Mahmoud Alaa", position: "Defender", age: 31, caps: 35 },
    { name: "Ahmed Fatouh", position: "Defender", age: 33, caps: 42 },
    { name: "Omar Gaber", position: "Defender", age: 32, caps: 52 },
    { name: "Akram Tawfik", position: "Defender", age: 26, caps: 22 },
    { name: "Mohamed Elneny", position: "Midfielder", age: 32, caps: 98 },
    { name: "Tarek Hamed", position: "Midfielder", age: 36, caps: 68 },
    { name: "Amr El-Solia", position: "Midfielder", age: 32, caps: 45 },
    { name: "Emam Ashour", position: "Midfielder", age: 26, caps: 28 },
    { name: "Ibrahim Adel", position: "Forward", age: 23, caps: 22 },
    { name: "Mohamed Salah", position: "Forward", age: 32, caps: 98 },
    { name: "Mostafa Mohamed", position: "Forward", age: 27, caps: 38 },
    { name: "Marwan Hamdi", position: "Forward", age: 30, caps: 18 },
    { name: "Trézéguet", position: "Forward", age: 30, caps: 58 },
    { name: "Omar Marmoush", position: "Forward", age: 25, caps: 28 },
    { name: "Ahmed Koka", position: "Forward", age: 31, caps: 22 },
    { name: "Ziad El-Shennawy", position: "Forward", age: 24, caps: 8 },
    { name: "Hussein El-Shahat", position: "Forward", age: 32, caps: 42 },
  ],
  'Ghana': [
    { name: "Lawrence Ati-Zigi", position: "Goalkeeper", age: 28, caps: 32 },
    { name: "Richard Ofori", position: "Goalkeeper", age: 30, caps: 22 },
    { name: "Daniel Amartey", position: "Defender", age: 29, caps: 52 },
    { name: "Mohammed Salisu", position: "Defender", age: 25, caps: 22 },
    { name: "Tariq Lamptey", position: "Defender", age: 24, caps: 18 },
    { name: "Gideon Mensah", position: "Defender", age: 26, caps: 25 },
    { name: "Alexander Djiku", position: "Defender", age: 30, caps: 28 },
    { name: "Denis Odoi", position: "Defender", age: 35, caps: 18 },
    { name: "Thomas Partey", position: "Midfielder", age: 31, caps: 52 },
    { name: "Mohammed Kudus", position: "Midfielder", age: 24, caps: 28 },
    { name: "André Ayew", position: "Midfielder", age: 35, caps: 120 },
    { name: "Elisha Owusu", position: "Midfielder", age: 27, caps: 12 },
    { name: "Salis Abdul Samed", position: "Midfielder", age: 24, caps: 15 },
    { name: "Jordan Ayew", position: "Forward", age: 33, caps: 98 },
    { name: "Inaki Williams", position: "Forward", age: 30, caps: 22 },
    { name: "Antoine Semenyo", position: "Forward", age: 24, caps: 18 },
    { name: "Osman Bukari", position: "Forward", age: 25, caps: 18 },
    { name: "Abdul Fatawu Issahaku", position: "Forward", age: 20, caps: 12 },
    { name: "Kamaldeen Sulemana", position: "Forward", age: 22, caps: 15 },
    { name: "Ernest Nuamah", position: "Forward", age: 21, caps: 8 },
  ],
  'Kaapverdië': [
    { name: "Vozinha", position: "Goalkeeper", age: 38, caps: 62 },
    { name: "Dylan Silva", position: "Goalkeeper", age: 28, caps: 15 },
    { name: "Roberto Lopes", position: "Defender", age: 32, caps: 28 },
    { name: "Steven Fortes", position: "Defender", age: 32, caps: 52 },
    { name: "Dylan Tavares", position: "Defender", age: 28, caps: 22 },
    { name: "Kenny Rocha", position: "Midfielder", age: 31, caps: 35 },
    { name: "Nuno Borges", position: "Midfielder", age: 29, caps: 28 },
    { name: "Patrick Andrade", position: "Midfielder", age: 29, caps: 32 },
    { name: "Jamiro Monteiro", position: "Midfielder", age: 31, caps: 28 },
    { name: "Jovane Cabral", position: "Forward", age: 26, caps: 22 },
    { name: "Ryan Mendes", position: "Forward", age: 34, caps: 58 },
    { name: "Garry Rodrigues", position: "Forward", age: 34, caps: 42 },
    { name: "Héldon", position: "Forward", age: 36, caps: 48 },
    { name: "Lisandro Semedo", position: "Defender", age: 28, caps: 18 },
    { name: "Logan Costa", position: "Defender", age: 23, caps: 8 },
    { name: "Weslley Patrik", position: "Forward", age: 26, caps: 15 },
    { name: "Tiago Rodrigues", position: "Forward", age: 28, caps: 12 },
    { name: "Gilson Benchimol", position: "Midfielder", age: 27, caps: 18 },
    { name: "Jeffry Fortes", position: "Defender", age: 28, caps: 22 },
    { name: "Dúdú", position: "Forward", age: 25, caps: 10 },
  ],
  'Marokko': [
    { name: "Yassine Bounou", position: "Goalkeeper", age: 33, caps: 72 },
    { name: "Munir El Kajoui", position: "Goalkeeper", age: 35, caps: 15 },
    { name: "Achraf Hakimi", position: "Defender", age: 26, caps: 78 },
    { name: "Nayef Aguerd", position: "Defender", age: 28, caps: 42 },
    { name: "Noussair Mazraoui", position: "Defender", age: 27, caps: 28 },
    { name: "Romain Saïss", position: "Defender", age: 34, caps: 82 },
    { name: "Jawad El Yamiq", position: "Defender", age: 32, caps: 28 },
    { name: "Sofyan Amrabat", position: "Midfielder", age: 28, caps: 62 },
    { name: "Azzedine Ounahi", position: "Midfielder", age: 24, caps: 32 },
    { name: "Selim Amallah", position: "Midfielder", age: 28, caps: 22 },
    { name: "Bilal El Khannouss", position: "Midfielder", age: 20, caps: 15 },
    { name: "Ilias Chair", position: "Midfielder", age: 27, caps: 18 },
    { name: "Hakim Ziyech", position: "Forward", age: 31, caps: 52 },
    { name: "Youssef En-Nesyri", position: "Forward", age: 27, caps: 72 },
    { name: "Sofiane Boufal", position: "Forward", age: 31, caps: 48 },
    { name: "Abdelhamid Sabiri", position: "Forward", age: 27, caps: 22 },
    { name: "Brahim Díaz", position: "Forward", age: 25, caps: 18 },
    { name: "Ayoub El Kaabi", position: "Forward", age: 31, caps: 18 },
    { name: "Zakaria Aboukhlal", position: "Forward", age: 24, caps: 22 },
    { name: "Abde Ezzalzouli", position: "Forward", age: 23, caps: 8 },
  ],
  'Tunesië': [
    { name: "Aymen Dahmen", position: "Goalkeeper", age: 27, caps: 18 },
    { name: "Mouez Hassen", position: "Goalkeeper", age: 29, caps: 22 },
    { name: "Dylan Bronn", position: "Defender", age: 29, caps: 48 },
    { name: "Montassar Talbi", position: "Defender", age: 26, caps: 28 },
    { name: "Ali Abdi", position: "Defender", age: 31, caps: 32 },
    { name: "Mohamed Dräger", position: "Defender", age: 28, caps: 35 },
    { name: "Wajdi Kechrida", position: "Defender", age: 29, caps: 22 },
    { name: "Aïssa Laïdouni", position: "Midfielder", age: 28, caps: 35 },
    { name: "Ellyes Skhiri", position: "Midfielder", age: 29, caps: 52 },
    { name: "Mohamed Ali Ben Romdhane", position: "Midfielder", age: 25, caps: 28 },
    { name: "Hannibal Mejbri", position: "Midfielder", age: 21, caps: 18 },
    { name: "Naïm Sliti", position: "Midfielder", age: 32, caps: 72 },
    { name: "Wahbi Khazri", position: "Forward", age: 33, caps: 78 },
    { name: "Youssef Msakni", position: "Forward", age: 34, caps: 92 },
    { name: "Seifeddine Jaziri", position: "Forward", age: 31, caps: 32 },
    { name: "Issam Jebali", position: "Forward", age: 33, caps: 28 },
    { name: "Saif-Eddine Khaoui", position: "Forward", age: 29, caps: 18 },
    { name: "Taha Yassine Khenissi", position: "Forward", age: 32, caps: 35 },
    { name: "Ferjani Sassi", position: "Midfielder", age: 32, caps: 62 },
    { name: "Ghaylen Chaaleli", position: "Forward", age: 29, caps: 22 },
  ],
  'Zuid-Afrika': [
    { name: "Ronwen Williams", position: "Goalkeeper", age: 32, caps: 52 },
    { name: "Veli Mothwa", position: "Goalkeeper", age: 31, caps: 12 },
    { name: "Siyanda Xulu", position: "Defender", age: 33, caps: 42 },
    { name: "Rushine De Reuck", position: "Defender", age: 28, caps: 22 },
    { name: "Khuliso Mudau", position: "Defender", age: 25, caps: 28 },
    { name: "Aubrey Modiba", position: "Defender", age: 29, caps: 18 },
    { name: "Nyiko Mobbie", position: "Defender", age: 28, caps: 12 },
    { name: "Teboho Mokoena", position: "Midfielder", age: 27, caps: 38 },
    { name: "Themba Zwane", position: "Midfielder", age: 35, caps: 42 },
    { name: "Ethan Brooks", position: "Midfielder", age: 22, caps: 12 },
    { name: "Mothobi Mvala", position: "Midfielder", age: 29, caps: 28 },
    { name: "Sphephelo Sithole", position: "Midfielder", age: 26, caps: 18 },
    { name: "Percy Tau", position: "Forward", age: 30, caps: 52 },
    { name: "Evidence Makgopa", position: "Forward", age: 24, caps: 18 },
    { name: "Lebo Mothiba", position: "Forward", age: 28, caps: 22 },
    { name: "Iqraam Rayners", position: "Forward", age: 28, caps: 8 },
    { name: "Themba Sikhakhane", position: "Forward", age: 25, caps: 5 },
    { name: "Oswin Appollis", position: "Forward", age: 23, caps: 12 },
    { name: "Elias Mokwana", position: "Forward", age: 24, caps: 5 },
    { name: "Patrick Maswanganyi", position: "Midfielder", age: 26, caps: 15 },
  ],
  'Senegal': [
    { name: "Édouard Mendy", position: "Goalkeeper", age: 32, caps: 32 },
    { name: "Alfred Gomis", position: "Goalkeeper", age: 31, caps: 15 },
    { name: "Kalidou Koulibaly", position: "Defender", age: 33, caps: 72 },
    { name: "Abdou Diallo", position: "Defender", age: 28, caps: 42 },
    { name: "Youssouf Sabaly", position: "Defender", age: 31, caps: 28 },
    { name: "Formose Mendy", position: "Defender", age: 25, caps: 18 },
    { name: "Pape Abou Cissé", position: "Defender", age: 29, caps: 22 },
    { name: "Idrissa Gueye", position: "Midfielder", age: 35, caps: 108 },
    { name: "Cheikhou Kouyaté", position: "Midfielder", age: 35, caps: 92 },
    { name: "Nampalys Mendy", position: "Midfielder", age: 32, caps: 38 },
    { name: "Pape Matar Sarr", position: "Midfielder", age: 22, caps: 22 },
    { name: "Pathé Ciss", position: "Midfielder", age: 30, caps: 28 },
    { name: "Sadio Mané", position: "Forward", age: 32, caps: 102 },
    { name: "Ismaïla Sarr", position: "Forward", age: 26, caps: 52 },
    { name: "Boulaye Dia", position: "Forward", age: 28, caps: 28 },
    { name: "Nicolas Jackson", position: "Forward", age: 23, caps: 18 },
    { name: "Iliman Ndiaye", position: "Forward", age: 24, caps: 22 },
    { name: "Habib Diallo", position: "Forward", age: 29, caps: 28 },
    { name: "Krépin Diatta", position: "Forward", age: 25, caps: 32 },
    { name: "Moussa Niakhaté", position: "Defender", age: 28, caps: 18 },
  ],
  'Ivoorkust': [
    { name: "Badra Ali Sangaré", position: "Goalkeeper", age: 29, caps: 22 },
    { name: "Yahia Fofana", position: "Goalkeeper", age: 26, caps: 12 },
    { name: "Serge Aurier", position: "Defender", age: 31, caps: 82 },
    { name: "Eric Bailly", position: "Defender", age: 30, caps: 42 },
    { name: "Ghislain Konan", position: "Defender", age: 28, caps: 28 },
    { name: "Simon Adingra", position: "Defender", age: 22, caps: 22 },
    { name: "Odilon Kossounou", position: "Defender", age: 23, caps: 28 },
    { name: "Willy Boly", position: "Defender", age: 33, caps: 28 },
    { name: "Franck Kessié", position: "Midfielder", age: 28, caps: 72 },
    { name: "Seko Fofana", position: "Midfielder", age: 29, caps: 28 },
    { name: "Jean Michaël Seri", position: "Midfielder", age: 33, caps: 48 },
    { name: "Ibrahim Sangaré", position: "Midfielder", age: 27, caps: 32 },
    { name: "Jeremie Boga", position: "Forward", age: 27, caps: 18 },
    { name: "Sébastien Haller", position: "Forward", age: 30, caps: 32 },
    { name: "Nicolas Pépé", position: "Forward", age: 29, caps: 42 },
    { name: "Wilfried Zaha", position: "Forward", age: 32, caps: 28 },
    { name: "Maxwell Cornet", position: "Forward", age: 28, caps: 35 },
    { name: "Christian Kouamé", position: "Forward", age: 27, caps: 22 },
    { name: "Oumar Diakité", position: "Forward", age: 21, caps: 8 },
    { name: "Karim Konaté", position: "Forward", age: 20, caps: 12 },
  ],
  'Australië': [
    { name: "Mat Ryan", position: "Goalkeeper", age: 32, caps: 85 },
    { name: "Andrew Redmayne", position: "Goalkeeper", age: 35, caps: 8 },
    { name: "Aziz Behich", position: "Defender", age: 33, caps: 58 },
    { name: "Miloš Degenek", position: "Defender", age: 30, caps: 48 },
    { name: "Harry Souttar", position: "Defender", age: 26, caps: 22 },
    { name: "Kye Rowles", position: "Defender", age: 26, caps: 18 },
    { name: "Nathaniel Atkinson", position: "Defender", age: 25, caps: 15 },
    { name: "Aaron Mooy", position: "Midfielder", age: 34, caps: 58 },
    { name: "Jackson Irvine", position: "Midfielder", age: 31, caps: 62 },
    { name: "Riley McGree", position: "Midfielder", age: 26, caps: 28 },
    { name: "Keanu Baccus", position: "Midfielder", age: 26, caps: 18 },
    { name: "Cameron Devlin", position: "Midfielder", age: 26, caps: 12 },
    { name: "Mathew Leckie", position: "Forward", age: 33, caps: 82 },
    { name: "Jamie Maclaren", position: "Forward", age: 31, caps: 28 },
    { name: "Martin Boyle", position: "Forward", age: 31, caps: 22 },
    { name: "Craig Goodwin", position: "Forward", age: 33, caps: 22 },
    { name: "Mitchell Duke", position: "Forward", age: 33, caps: 28 },
    { name: "Awer Mabil", position: "Forward", age: 29, caps: 28 },
    { name: "Garang Kuol", position: "Forward", age: 20, caps: 8 },
    { name: "Nestory Irankunda", position: "Forward", age: 18, caps: 5 },
  ],
  'Iran': [
    { name: "Alireza Beiranvand", position: "Goalkeeper", age: 32, caps: 72 },
    { name: "Amir Abedzadeh", position: "Goalkeeper", age: 31, caps: 18 },
    { name: "Shoja Khalilzadeh", position: "Defender", age: 35, caps: 52 },
    { name: "Ramin Rezaeian", position: "Defender", age: 34, caps: 58 },
    { name: "Milad Mohammadi", position: "Defender", age: 31, caps: 62 },
    { name: "Sadegh Moharrami", position: "Defender", age: 28, caps: 28 },
    { name: "Hossein Kanaani", position: "Defender", age: 28, caps: 35 },
    { name: "Saeid Ezatolahi", position: "Midfielder", age: 28, caps: 58 },
    { name: "Ahmad Nourollahi", position: "Midfielder", age: 31, caps: 52 },
    { name: "Saman Ghoddos", position: "Midfielder", age: 31, caps: 42 },
    { name: "Alireza Jahanbakhsh", position: "Midfielder", age: 31, caps: 72 },
    { name: "Ali Karimi", position: "Midfielder", age: 30, caps: 28 },
    { name: "Mehdi Taremi", position: "Forward", age: 32, caps: 78 },
    { name: "Sardar Azmoun", position: "Forward", age: 29, caps: 72 },
    { name: "Karim Ansarifard", position: "Forward", age: 34, caps: 98 },
    { name: "Vahid Amiri", position: "Forward", age: 36, caps: 72 },
    { name: "Reza Asadi", position: "Forward", age: 26, caps: 18 },
    { name: "Shahab Zahedi", position: "Forward", age: 29, caps: 22 },
    { name: "Allahyar Sayyadmanesh", position: "Forward", age: 23, caps: 22 },
    { name: "Mehdi Ghayedi", position: "Forward", age: 25, caps: 28 },
  ],
  'Japan': [
    { name: "Shuichi Gonda", position: "Goalkeeper", age: 35, caps: 38 },
    { name: "Zion Suzuki", position: "Goalkeeper", age: 22, caps: 8 },
    { name: "Takehiro Tomiyasu", position: "Defender", age: 26, caps: 42 },
    { name: "Ko Itakura", position: "Defender", age: 28, caps: 28 },
    { name: "Maya Yoshida", position: "Defender", age: 36, caps: 128 },
    { name: "Hiroki Sakai", position: "Defender", age: 34, caps: 72 },
    { name: "Miki Yamane", position: "Defender", age: 31, caps: 18 },
    { name: "Wataru Endo", position: "Midfielder", age: 31, caps: 58 },
    { name: "Hidemasa Morita", position: "Midfielder", age: 29, caps: 32 },
    { name: "Takumi Minamino", position: "Midfielder", age: 30, caps: 52 },
    { name: "Ritsu Doan", position: "Midfielder", age: 26, caps: 42 },
    { name: "Kaoru Mitoma", position: "Midfielder", age: 27, caps: 28 },
    { name: "Junya Ito", position: "Forward", age: 31, caps: 48 },
    { name: "Takuma Asano", position: "Forward", age: 30, caps: 42 },
    { name: "Ayase Ueda", position: "Forward", age: 26, caps: 22 },
    { name: "Kyogo Furuhashi", position: "Forward", age: 29, caps: 18 },
    { name: "Daichi Kamada", position: "Midfielder", age: 28, caps: 35 },
    { name: "Ao Tanaka", position: "Midfielder", age: 26, caps: 28 },
    { name: "Keito Nakamura", position: "Forward", age: 24, caps: 12 },
    { name: "Shuto Machino", position: "Forward", age: 25, caps: 8 },
  ],
  'Jordanië': [
    { name: "Yazeed Abulaila", position: "Goalkeeper", age: 32, caps: 52 },
    { name: "Mohammad Shatnawi", position: "Goalkeeper", age: 28, caps: 18 },
    { name: "Anas Bani Yaseen", position: "Defender", age: 35, caps: 78 },
    { name: "Salem Al-Ajalin", position: "Defender", age: 32, caps: 42 },
    { name: "Abdullah Nasib", position: "Defender", age: 28, caps: 35 },
    { name: "Feras Shelbaieh", position: "Defender", age: 29, caps: 28 },
    { name: "Abdallah Al-Olaimat", position: "Defender", age: 27, caps: 22 },
    { name: "Mousa Al-Taamari", position: "Midfielder", age: 27, caps: 52 },
    { name: "Yazan Al-Naimat", position: "Midfielder", age: 25, caps: 28 },
    { name: "Nizar Al-Rashdan", position: "Midfielder", age: 29, caps: 35 },
    { name: "Baha' Faisal", position: "Midfielder", age: 29, caps: 38 },
    { name: "Ehsan Haddad", position: "Midfielder", age: 28, caps: 22 },
    { name: "Ahmad Ersan", position: "Forward", age: 30, caps: 42 },
    { name: "Hamza Al-Dardour", position: "Forward", age: 35, caps: 82 },
    { name: "Yazan Al-Arab", position: "Forward", age: 26, caps: 18 },
    { name: "Ali Olwan", position: "Forward", age: 25, caps: 22 },
    { name: "Oday Dabbagh", position: "Forward", age: 26, caps: 15 },
    { name: "Yousef Rawshdeh", position: "Forward", age: 24, caps: 12 },
    { name: "Mohammad Abu Zraiq", position: "Midfielder", age: 30, caps: 32 },
    { name: "Amer Jamous", position: "Defender", age: 28, caps: 18 },
  ],
  'Oezbekistan': [
    { name: "Eldor Suyunov", position: "Goalkeeper", age: 27, caps: 22 },
    { name: "Utkir Yusupov", position: "Goalkeeper", age: 30, caps: 15 },
    { name: "Husniddin Aliqulov", position: "Defender", age: 30, caps: 42 },
    { name: "Abdukodir Khusanov", position: "Defender", age: 20, caps: 18 },
    { name: "Islom Kobilov", position: "Defender", age: 27, caps: 28 },
    { name: "Davronbek Khashimov", position: "Defender", age: 24, caps: 22 },
    { name: "Rustam Ashurmatov", position: "Defender", age: 26, caps: 18 },
    { name: "Otabek Shukurov", position: "Midfielder", age: 29, caps: 58 },
    { name: "Jaloliddin Masharipov", position: "Midfielder", age: 31, caps: 72 },
    { name: "Jamshid Iskanderov", position: "Midfielder", age: 27, caps: 32 },
    { name: "Hojiakbar Alijonov", position: "Midfielder", age: 26, caps: 22 },
    { name: "Abbosbek Fayzullayev", position: "Midfielder", age: 20, caps: 12 },
    { name: "Eldor Shomurodov", position: "Forward", age: 29, caps: 62 },
    { name: "Igor Sergeev", position: "Forward", age: 30, caps: 28 },
    { name: "Zafarmurod Kambarov", position: "Forward", age: 27, caps: 18 },
    { name: "Khusain Norchaev", position: "Forward", age: 25, caps: 15 },
    { name: "Jasurbek Jaloliddinov", position: "Midfielder", age: 26, caps: 22 },
    { name: "Azizbek Turgunboev", position: "Forward", age: 24, caps: 12 },
    { name: "Sardor Rashidov", position: "Forward", age: 34, caps: 48 },
    { name: "Bobur Abdikholikov", position: "Forward", age: 24, caps: 8 },
  ],
  'Qatar': [
    { name: "Meshaal Barsham", position: "Goalkeeper", age: 27, caps: 28 },
    { name: "Saad Al Sheeb", position: "Goalkeeper", age: 34, caps: 82 },
    { name: "Pedro Miguel", position: "Defender", age: 34, caps: 72 },
    { name: "Bassam Al-Rawi", position: "Defender", age: 27, caps: 52 },
    { name: "Abdelkarim Hassan", position: "Defender", age: 31, caps: 138 },
    { name: "Boualem Khoukhi", position: "Defender", age: 34, caps: 78 },
    { name: "Tarek Salman", position: "Defender", age: 27, caps: 28 },
    { name: "Hassan Al-Haydos", position: "Midfielder", age: 34, caps: 172 },
    { name: "Abdulaziz Hatem", position: "Midfielder", age: 34, caps: 82 },
    { name: "Karim Boudiaf", position: "Midfielder", age: 34, caps: 92 },
    { name: "Assim Madibo", position: "Midfielder", age: 28, caps: 35 },
    { name: "Ismaeel Mohammad", position: "Midfielder", age: 34, caps: 72 },
    { name: "Akram Afif", position: "Forward", age: 27, caps: 82 },
    { name: "Almoez Ali", position: "Forward", age: 28, caps: 108 },
    { name: "Mohammed Muntari", position: "Forward", age: 31, caps: 52 },
    { name: "Ahmed Alaaeldin", position: "Forward", age: 31, caps: 58 },
    { name: "Yusuf Abdurisag", position: "Forward", age: 27, caps: 18 },
    { name: "Khalid Muneer", position: "Forward", age: 26, caps: 22 },
    { name: "Mohammed Waad", position: "Forward", age: 25, caps: 12 },
    { name: "Mubarak Shani", position: "Midfielder", age: 24, caps: 8 },
  ],
  'Zuid-Korea': [
    { name: "Kim Seung-gyu", position: "Goalkeeper", age: 34, caps: 62 },
    { name: "Jo Hyeon-woo", position: "Goalkeeper", age: 33, caps: 28 },
    { name: "Kim Min-jae", position: "Defender", age: 28, caps: 52 },
    { name: "Kim Young-gwon", position: "Defender", age: 34, caps: 108 },
    { name: "Kim Jin-su", position: "Defender", age: 32, caps: 72 },
    { name: "Yoon Jong-gyu", position: "Defender", age: 25, caps: 18 },
    { name: "Kim Tae-hwan", position: "Defender", age: 35, caps: 42 },
    { name: "Son Heung-min", position: "Forward", age: 32, caps: 118 },
    { name: "Hwang In-beom", position: "Midfielder", age: 28, caps: 52 },
    { name: "Lee Jae-sung", position: "Midfielder", age: 32, caps: 62 },
    { name: "Jung Woo-young", position: "Midfielder", age: 35, caps: 105 },
    { name: "Hwang Hee-chan", position: "Forward", age: 28, caps: 52 },
    { name: "Lee Kang-in", position: "Midfielder", age: 23, caps: 48 },
    { name: "Cho Gue-sung", position: "Forward", age: 26, caps: 32 },
    { name: "Song Min-kyu", position: "Forward", age: 25, caps: 22 },
    { name: "Na Sang-ho", position: "Forward", age: 28, caps: 28 },
    { name: "Oh Se-hun", position: "Forward", age: 25, caps: 12 },
    { name: "Jeong Sang-bin", position: "Forward", age: 22, caps: 8 },
    { name: "Bae Jun-ho", position: "Midfielder", age: 21, caps: 8 },
    { name: "Yang Hyun-jun", position: "Midfielder", age: 22, caps: 12 },
  ],
  'Saoedi-Arabië': [
    { name: "Mohammed Al-Owais", position: "Goalkeeper", age: 33, caps: 72 },
    { name: "Fawaz Al-Qarni", position: "Goalkeeper", age: 30, caps: 15 },
    { name: "Yasser Al-Shahrani", position: "Defender", age: 32, caps: 82 },
    { name: "Ali Al-Bulaihi", position: "Defender", age: 35, caps: 58 },
    { name: "Abdulelah Al-Amri", position: "Defender", age: 27, caps: 28 },
    { name: "Saud Abdulhamid", position: "Defender", age: 25, caps: 32 },
    { name: "Hassan Kadesh", position: "Defender", age: 28, caps: 22 },
    { name: "Salman Al-Faraj", position: "Midfielder", age: 35, caps: 78 },
    { name: "Salem Al-Dawsari", position: "Midfielder", age: 33, caps: 82 },
    { name: "Abdulellah Al-Malki", position: "Midfielder", age: 30, caps: 42 },
    { name: "Mohammed Kanno", position: "Midfielder", age: 30, caps: 52 },
    { name: "Nasser Al-Dawsari", position: "Midfielder", age: 25, caps: 22 },
    { name: "Firas Al-Buraikan", position: "Forward", age: 24, caps: 42 },
    { name: "Saleh Al-Shehri", position: "Forward", age: 31, caps: 52 },
    { name: "Fahad Al-Muwallad", position: "Forward", age: 30, caps: 72 },
    { name: "Hattan Bahebri", position: "Forward", age: 32, caps: 28 },
    { name: "Abdullah Radif", position: "Forward", age: 25, caps: 18 },
    { name: "Ayman Yahya", position: "Forward", age: 24, caps: 22 },
    { name: "Nawaf Al-Aqidi", position: "Goalkeeper", age: 25, caps: 8 },
    { name: "Hassan Al-Tambakti", position: "Defender", age: 25, caps: 28 },
  ],
  'Nieuw-Zeeland': [
    { name: "Stefan Marinovic", position: "Goalkeeper", age: 33, caps: 28 },
    { name: "Oliver Sail", position: "Goalkeeper", age: 28, caps: 22 },
    { name: "Winston Reid", position: "Defender", age: 36, caps: 52 },
    { name: "Tommy Smith", position: "Defender", age: 34, caps: 42 },
    { name: "Michael Boxall", position: "Defender", age: 36, caps: 48 },
    { name: "Nando Pijnaker", position: "Defender", age: 29, caps: 28 },
    { name: "Liberato Cacace", position: "Defender", age: 23, caps: 22 },
    { name: "Tim Payne", position: "Defender", age: 31, caps: 18 },
    { name: "Joe Bell", position: "Midfielder", age: 25, caps: 32 },
    { name: "Marko Stamenic", position: "Midfielder", age: 24, caps: 22 },
    { name: "Matt Garbett", position: "Midfielder", age: 23, caps: 18 },
    { name: "Sarpreet Singh", position: "Midfielder", age: 25, caps: 18 },
    { name: "Elijah Just", position: "Midfielder", age: 27, caps: 22 },
    { name: "Chris Wood", position: "Forward", age: 33, caps: 72 },
    { name: "Kosta Barbarouses", position: "Forward", age: 34, caps: 52 },
    { name: "Callum McCowatt", position: "Forward", age: 25, caps: 22 },
    { name: "Ben Waine", position: "Forward", age: 23, caps: 18 },
    { name: "Matthew Garbett", position: "Forward", age: 22, caps: 12 },
    { name: "Alex Greive", position: "Forward", age: 24, caps: 8 },
    { name: "Logan Rogerson", position: "Forward", age: 26, caps: 15 },
  ],
};

// Map position names to Dutch
const positionMap: Record<string, string> = {
  'Goalkeeper': 'Keeper',
  'Defender': 'Verdediger',
  'Midfielder': 'Middenvelder',
  'Forward': 'Aanvaller',
};

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { country = 'België' } = await req.json().catch(() => ({}));
    
    const firecrawlApiKey = Deno.env.get('FIRECRAWL_API_KEY');
    if (!firecrawlApiKey) {
      console.error('FIRECRAWL_API_KEY not configured');
      return new Response(
        JSON.stringify({ success: false, error: 'Firecrawl connector not configured' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    console.log(`Processing ${country} national team players...`);

    // Get players for the requested country
    const knownPlayers = countryPlayers[country];
    
    if (!knownPlayers) {
      return new Response(
        JSON.stringify({ 
          success: false, 
          error: `Country "${country}" not supported. Available: ${Object.keys(countryPlayers).join(', ')}` 
        }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const players: PlayerData[] = [];
    
    console.log(`Processing ${knownPlayers.length} players for ${country}...`);
    
    for (const player of knownPlayers) {
      players.push({
        name: player.name,
        position: positionMap[player.position] || player.position,
        age: player.age,
        international_caps: player.caps,
        image_url: null, // Images fetched separately via fetch-player-images
      });
    }

    console.log(`Processed ${players.length} players`);

    // Get existing players from this country
    const { data: existingPlayers, error: fetchError } = await supabase
      .from('wk_players')
      .select('name')
      .eq('country', country);

    if (fetchError) {
      console.error('Error fetching existing players:', fetchError);
    }

    const existingNames = new Set(existingPlayers?.map(p => p.name.toLowerCase()) || []);
    
    // Filter out players that already exist
    const newPlayers = players.filter(p => !existingNames.has(p.name.toLowerCase()));
    const existingToUpdate = players.filter(p => existingNames.has(p.name.toLowerCase()));

    console.log(`New players to add: ${newPlayers.length}`);
    console.log(`Existing players to update: ${existingToUpdate.length}`);

    // Insert new players
    if (newPlayers.length > 0) {
      const { data: insertedPlayers, error: insertError } = await supabase
        .from('wk_players')
        .insert(
          newPlayers.map(p => ({
            name: p.name,
            country: country,
            position: p.position,
            age: p.age,
            goals: 0,
            international_caps: p.international_caps,
            image_url: p.image_url,
          }))
        )
        .select();

      if (insertError) {
        console.error('Error inserting players:', insertError);
      } else {
        console.log(`Inserted ${insertedPlayers?.length} new players`);
      }
    }

    // Update existing players
    for (const player of existingToUpdate) {
      const { error: updateError } = await supabase
        .from('wk_players')
        .update({ 
          international_caps: player.international_caps,
          age: player.age,
          position: player.position,
        })
        .eq('name', player.name)
        .eq('country', country);

      if (updateError) {
        console.error(`Error updating ${player.name}:`, updateError);
      }
    }

    return new Response(
      JSON.stringify({
        success: true,
        message: `Processed ${players.length} ${country} players`,
        newPlayersAdded: newPlayers.length,
        existingPlayersUpdated: existingToUpdate.length,
        availableCountries: Object.keys(countryPlayers),
        players: players.map(p => ({ name: p.name, position: p.position })),
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  } catch (error) {
    console.error('Error processing players:', error);
    const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred';
    return new Response(
      JSON.stringify({ success: false, error: errorMessage }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
